name: Docker Image CI

on:
  release:
    types: [ published ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
       
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          jekewa/b2evolution
        tags: |
          type=semver,pattern={{version}}
      
    - name: Docker meta SSL
      id: meta_ssl
      uses: docker/metadata-action@v3
      with:
        images: |
          jekewa/b2evolution
        flavor: |
          prefix=ssl-,onlatest=true
        tags: |
          type=semver,pattern={{version}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Git b2evolution.net
      run: ./gitclone.sh
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
      
    - name: Build and push SSL
      id: docker_build_ssl
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile-ssl
        push: true
        tags: ${{ steps.meta_ssl.outputs.tags }}
        labels: ${{ steps.meta_ssl.outputs.labels }}
